### PR TITLE
feature/fix-build

### PR DESCRIPTION
**Pull request by ghost**
While internal Jenkins builds were failing for configuration related reasons, this PR updates testing to our new standard. 

PR includes:
- Cookbook cleanup
- Updated ruby dev version
- Updated gem and cookbook dependencies (explicitly stated)
- Added Rake task for Jenkins builds
- Rubocop syntax fixes

### CODE REVIEW

**Comment by medidata** [comment]
Test failed. :poop:
Refer to this link for build results: http://ec2-107-22-53-102.compute-1.amazonaws.com:8080/job/chronos_test/1/

**Comment by medidata** [comment]
Test failed. :poop:
Refer to this link for build results: http://ec2-107-22-53-102.compute-1.amazonaws.com:8080/job/chronos_test/2/

**Comment by medidata** [comment]
Test PASSED! :thumbsup:
Refer to this link for build results: http://ec2-107-22-53-102.compute-1.amazonaws.com:8080/job/chronos_test/3/

**Comment by medidata** [comment]
Test failed. :poop:
Refer to this link for build results: http://ec2-107-22-53-102.compute-1.amazonaws.com:8080/job/chronos_test/4/

**Comment by harryw** [comment]
test this please

**Comment by medidata** [comment]
Test failed. :poop:
Refer to this link for build results: http://ec2-107-22-53-102.compute-1.amazonaws.com:8080/job/chronos_test/6/

**Comment by harryw** [comment]
@mjcdiggity Do you plan to return to this PR soon or shall we close it?

**Comment by ghost** [comment]
@harryw Let's close this, as most of the work here will need to change. I'll make a new PR to fix this.

**Pull request closed without merging**
